const IS_APP_LOADING = "app/IS_APP_LOADING";
const CURRENT_LOADER_TYPES = "app/CURRENT_LOADER_TYPES";
const ERROR_INFO = "app/ERROR_INFO";
const SELECTED_NAV_MENU = "app/SELECTED_NAV_MENU";
const RIGHT_NAV = "app/RIGHT_NAV";
const LEFT_NAV = "app/LEFT_NAV";
const SELECTED_LANGUAGE = "app/SELECTED_LANGUAGE";
const PIN_NAV = "app/PIN_NAV";
const SCREEN_HEADER_INFO = "app/SCREEN_HEADER_INFO";
const FETCH_CALL_SUCCEEDED = "app/FETCH_CALL_SUCCEEDED";
const SEARCH_TEXT = "app/SEARCH_TEXT";
const CURRENT_DATE_AND_TIME = "app/CURRENT_DATE_AND_TIME";
const TIME_DIFF = "app/TIME_DIFF";
const RESET = "app/RESET";
const RAID_STATUS = "app/RAID_STATUS";
const IMB_STATUS = "app/IMB_STATUS";
const AUDIO_DEVICES = "audio/status";
const RESET_PROFILE = "app/RESET_PROFILE";

export {
  IS_APP_LOADING,
  ERROR_INFO,
  SELECTED_NAV_MENU,
  CURRENT_LOADER_TYPES,
  RIGHT_NAV,
  LEFT_NAV,
  PIN_NAV,
  SEARCH_TEXT,
  RESET,
  CURRENT_DATE_AND_TIME,
  TIME_DIFF,
  SCREEN_HEADER_INFO,
  SELECTED_LANGUAGE,
  FETCH_CALL_SUCCEEDED,
  RAID_STATUS,
  IMB_STATUS,
  AUDIO_DEVICES,
  RESET_PROFILE,
};
