const IS_LOADING = "user/IS_LOADING";
const IS_ERROR = "user/IS_ERROR";
const LOGIN_USER = "user/LOGIN_USER";
const LOGOUT_USER = "user/LOGOUT_USER";
const PASSWORD = "user/PASSWORD";
const IS_FORM_NOT_SAVED = "user/IS_FORM_NOT_SAVED";
const CHANGED_SETTINGS = "user/CHANGED_SETTINGS";
const NEW_PASSWORD = "user/NEW_PASSWORD";
const EMPTY_FORM_FIELDS = "setting/ EMPTY_FORM_FIELDS";
const PROFILE_NAME = "user/PROFILE_NAME";
const PASSWORD_ERROR = "user/PASSWORD_ERROR";

export {
  IS_LOADING,
  IS_ERROR,
  LOGIN_USER,
  LOGOUT_USER,
  PASSWORD,
  IS_FORM_NOT_SAVED,
  CHANGED_SETTINGS,
  NEW_PASSWORD,
  EMPTY_FORM_FIELDS,
  PROFILE_NAME,
  PASSWORD_ERROR,
};
